# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e306ffbf534fd313d30e1ae63cb46cc8e55f04cac97c8d7b512bb76206ed81a116a66b9a5022d37a2db0e1afcd792ff516c8d54c99fdfaf5e5410f66304a401

test:
  secret_key_base: 159ff4ab0f865fde83d321d4d8857d7720878aa5ba9fc36ea2813553d93869796bcb9e5e2a6615427a087342c57506a0824d91c74ecff316d6032fb5d322f50e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
