module ApplicationHelper

    COUNTIES = %w(AB AR AG BC BH BN BT BV B BR BZ CS CL CJ CT CV DB DJ GL GR GJ HR HD IL IS IF MM MH MS NT OT PH SM SJ SB SV TR TM TL VS VL VN)

    HASH_COUNTIES = {
      AB: 'Alba',
      AR: 'Arad',
      AG: 'Arges',
      B:  'Bucuresti',
      BC: 'Bacau',
      BH: 'Bihor',
      BN: 'Bistrita-Nasaud',
      BT: 'Botosani',
      BV: 'Brasov',
      BR: 'Braila',
      BZ: 'Buzau',
      CS: 'Caras-Severin',
      CL: 'Calarasi',
      CJ: 'Cluj',
      CT: 'Constanta',
      CV: 'Covasna',
      DB: 'Dambovita',
      DJ: 'Dolj',
      GL: 'Galati',
      GR: 'Giurgiu',
      GJ: 'Gorj',
      HR: 'Harghita',
      HD: 'Hunedoara',
      IL: 'Ialomita',
      IS: 'Iasi',
      IF: 'Ilfov',
      MM: 'Maramures',
      MH: 'Mededinti',
      MS: 'Mures',
      NT: 'Neamt',
      OT: 'Olt',
      PH: 'Prahova',
      SM: 'Satu Mare',
      SJ: 'Salaj',
      SB: 'Sibiu',
      SV: 'Suceava',
      TR: 'Teleorman',
      TM: 'Timis',
      TL: 'Tulcea',
      VS: 'Vaslui',
      VL: 'Valcea',
      VN: 'Vrancea',
    }

end
